const endpoint='https://tmlintprfxqvgnyiifah.supabase.co/functions/v1/rsvp';
const form=document.querySelector('#lookupForm'),notice=document.querySelector('#notice'),invitation=document.querySelector('#invitation'),help=document.querySelector('#help');
const call=async body=>{const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json();return{ok:response.ok,data}};
async function loadStatus(){const{ok,data}=await call({action:'status'});if(!ok)return;if(data.closed){form.hidden=true;intro.textContent=data.configured?(data.contactCopy||'Online RSVP is currently closed.'):'Online RSVP isn\'t open yet. Please check back soon.';}}
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;notice.textContent='Looking for your invitation…';const {ok,data}=await call({action:'lookup',name:guestName.value,postalCode:postalCode.value});button.disabled=false;if(!ok){if(data.code==='POSTAL_REQUIRED'){postalLabel.hidden=false;postalCode.required=true;postalCode.focus();notice.textContent='Please add the mailing ZIP or postal code from your invitation.';return}notice.textContent=data.code==='RSVP_NOT_CONFIGURED'?'Online RSVP is not open yet.':'We could not find that invitation. Check the full name or request help below.';help.hidden=false;helpName.value=guestName.value;return}renderInvitation(data);});
function renderInvitation(data){const locked=data.closed||data.requiresPin;notice.textContent='';form.hidden=true;invitation.hidden=false;invitation.innerHTML=`<p class="eyebrow">${escape(data.householdName||'Your invitation')}</p><h2>Your invitation</h2>${data.closed?`<p class="closed-note">${escape(data.contactCopy||'Online RSVP is closed.')}</p>`:data.requiresPin?'<form id="pinForm"><label>Private edit PIN<input id="editPin" inputmode="numeric" pattern="[0-9]{6}" required></label><button type="submit">Unlock my RSVP</button><p id="pinNotice" role="status"></p></form>':''}<form id="responseForm">${data.guests.map(g=>`<article class="guest-rsvp"><h3>${escape(g.name)}</h3>${g.events.map(e=>`<div class="event-rsvp" data-guest-ref="${escape(g.ref)}" data-event-ref="${escape(e.ref)}"><strong>${escape(e.name||'Wedding event')}</strong><p>${escape([formatDate(e.startsAt),e.venue].filter(Boolean).join(' · '))}</p>${locked?`<span>${escape(e.status==='pending'?'Awaiting response':e.status)}</span>`:`<label>Will you attend?<select class="attendance" required><option value="">Choose…</option><option value="attending" ${e.status==='attending'?'selected':''}>Joyfully accepts</option><option value="declined" ${e.status==='declined'?'selected':''}>Regretfully declines</option></select></label><label>Dietary needs<input class="dietary" value="${escape(g.dietaryNotes||'')}"></label>${e.plusOneAllowed?'<label class="plus-toggle"><input class="plusAccepted" type="checkbox"> Bringing a plus-one</label><label>Plus-one name<input class="plusName"></label><label>Plus-one dietary needs<input class="plusDietary"></label>':''}`}</div>`).join('')}</article>`).join('')}${locked?'':'<button type="submit">Submit RSVP</button><p id="submitNotice" role="status"></p>'}</form>`;if(!locked)bindResponseForm(data.token);if(data.requiresPin)document.querySelector('#pinForm').addEventListener('submit',async event=>{event.preventDefault();const{ok,result}=await unlock(data.token,document.querySelector('#editPin').value);if(ok){data.token=result.token;data.requiresPin=false;renderInvitation(data)}else document.querySelector('#pinNotice').textContent=result.code==='PIN_LOCKED'?'Too many tries. Please wait 15 minutes.':'That PIN did not match.';});}
async function unlock(token,pin){const response=await call({action:'unlock-edit',token,pin});return{ok:response.ok,result:response.data}}
function bindResponseForm(token){const responseForm=document.querySelector('#responseForm'),idempotencyKey=crypto.randomUUID();responseForm.addEventListener('submit',async event=>{event.preventDefault();const button=responseForm.querySelector('button'),submitNotice=document.querySelector('#submitNotice');button.disabled=true;submitNotice.textContent='Saving your response…';const responses=[...responseForm.querySelectorAll('.event-rsvp')].map(row=>({guestRef:row.dataset.guestRef,eventRef:row.dataset.eventRef,status:row.querySelector('.attendance').value,dietaryNotes:row.querySelector('.dietary').value,plusOneAccepted:row.querySelector('.plusAccepted')?.checked||false,plusOneName:row.querySelector('.plusName')?.value||'',plusOneDietaryNotes:row.querySelector('.plusDietary')?.value||''}));const{ok,data}=await call({action:'submit',token,idempotencyKey,responses});if(!ok){button.disabled=false;submitNotice.textContent=data.code==='DEADLINE_CLOSED'?'Online RSVP has closed. Please contact Tucker or Sydney.':data.code==='RATE_LIMITED'?'Too many attempts. Please wait a few minutes.':'We could not confirm whether this saved. Please try once more.';return}responseForm.innerHTML=`<h2>Thank you—your RSVP is saved.</h2>${data.editPin?`<p class="closed-note">Your private edit PIN is <strong>${escape(data.editPin)}</strong>. Save it somewhere safe.</p>`:''}<p>Tucker and Sydney can now see your response.</p>`;});}
document.querySelector('#helpForm').addEventListener('submit',async event=>{event.preventDefault();const{ok}=await call({action:'help',name:helpName.value,contact:helpContact.value});if(ok){help.innerHTML='<h2>Request received</h2><p>Tucker or Sydney can review it privately.</p>'}});
const escape=value=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatDate=value=>value?new Date(value).toLocaleString(undefined,{month:'long',day:'numeric',hour:'numeric',minute:'2-digit'}):'';
loadStatus();
