import { bindLiveView, escapeHtml, guestsView, registryView, rsvpsView, settingsView } from './data.js?v=20260831-2';
import { supabase } from '../shared/supabase.js';

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const workspace = $('#workspace');

function weddingPreviewDetails(){
  const name=document.body.dataset.weddingName||'Your wedding';
  const parts=name.split(/\s+&\s+/);
  const heading=parts.length===2?`${escapeHtml(parts[0])}<br>&amp; ${escapeHtml(parts[1])}`:escapeHtml(name);
  const rawDate=document.body.dataset.weddingDate;
  const date=rawDate?new Date(`${rawDate}T12:00:00`).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'}):'Date to be announced';
  return {heading,date:escapeHtml(date)};
}

const views = {
room: () => `
  <div class="room-layout">
    <section class="room-main">
      <div class="room-head"><div><span class="eyebrow">Your shared space</span><h1>Good morning, you two.</h1><p class="page-intro">What can I take off your plate?</p></div><button class="button subtle demo" data-toast="Showing 12 recent changes">See recent changes</button></div>
      <div class="messages">
        <div class="message mine"><div class="bubble"><div class="bubble-meta"><b>Tucker</b> · 9:42 AM</div>Add Aunt Kim and give her a plus-one for the wedding.</div></div>
        <div class="message"><span class="message-avatar">G</span><div class="bubble"><div class="bubble-meta"><b>Grace</b> · just now</div>Done—I found Aunt Kim in your family notes and kept the update attributed to you.</div></div>
        <div class="action-card" id="auntAction"><div class="action-title"><span class="check">✓</span>Aunt Kim is on the list</div><div class="action-body">Wedding invitation · included<br>Plus-one · allowed<br>Invitation · still a draft</div><div class="chips"><button class="chip go" data-view="guests">Open guest card</button><button class="chip go" data-view="rsvps">Preview RSVP</button><button class="chip outline" id="undoAunt">Undo</button></div></div>
        <div class="message"><span class="message-avatar">G</span><div class="bubble"><div class="bubble-meta"><b>Grace</b></div>Your potential count is 147. I’ll keep her children separate until you and Syd decide.</div></div>
        <div class="action-card approval"><div class="action-title"><span class="check">!</span>Ready for both of you</div><div class="action-body"><b>Adults-only wording</b><br>“We adore your little ones, but our celebration will be adults only.”<br><br>This changes your public FAQ. Nothing is published yet.</div><div class="chips"><button class="chip demo" data-toast="Tucker approved — waiting for Syd">Approve</button><button class="chip outline demo" data-toast="Draft opened for editing">Edit wording</button></div></div>
      </div>
      <form class="composer" id="composer"><input id="chatInput" placeholder="Tell Grace what's on your mind…"><button class="send" aria-label="Send">↑</button></form>
    </section>
    <aside class="room-side"><h2 class="side-title">Your wedding, today</h2><p class="side-sub">The calm little snapshot behind the conversation.</p><div class="pulse-stats"><div class="pulse-stat"><strong>147</strong><span>sample guest count</span></div><div class="pulse-stat"><strong>2</strong><span>things to decide</span></div></div><div class="pulse-card"><h3>Waiting for both of you</h3><div class="pulse-line"><i class="dot"></i>Adults-only wording</div><div class="pulse-line"><i class="dot"></i>Welcome party guests</div></div><div class="pulse-card"><h3>Coming up</h3><div class="pulse-line"><i class="dot" style="background:#d49b43"></i>Confirm venue and date</div><div class="pulse-line"><i class="dot" style="background:#7da1aa"></i>Review save-the-date timing</div></div><div class="pulse-card"><h3>Your website</h3><div class="pulse-line"><i class="dot" style="background:#5f8068"></i>Private preview · 3 changes ready</div><button class="chip go" data-view="website">Review changes</button></div></aside>
  </div>`,
overview: () => pageHead('Wedding home','Manage the shared details behind your wedding and guest website.','Private couple workspace',`<a class="button subtle" href="../wedding/index.html">Open guest website ↗</a>`) + `
  <div class="home-actions">
    <button class="card home-action go" data-view="guests"><span class="home-action-icon">♙</span><strong>Guest list</strong><small>Households, guests, events, and RSVPs</small><b>Manage guests →</b></button>
    <button class="card home-action go" data-view="website"><span class="home-action-icon">✦</span><strong>Website</strong><small>Preview what your guests will see</small><b>Open website →</b></button>
    <button class="card home-action go" data-view="registry"><span class="home-action-icon">◇</span><strong>Registry</strong><small>Add, order, hide, or publish registry links</small><b>Manage registry →</b></button>
    <button class="card home-action go" data-view="settings"><span class="home-action-icon">⚙</span><strong>Settings</strong><small>Partner access, privacy, and account controls</small><b>Open settings →</b></button>
  </div>
  <div class="grid two home-secondary"><div><div class="section-title"><h2>Next steps</h2><a class="go" data-view="tasks">Planning tools</a></div><div class="card"><div class="task-row"><span class="fake-check"></span><div class="task-copy"><strong>Build your private guest list</strong><span>Add households first, then assign guests to events.</span></div><button class="chip go" data-view="guests">Open</button></div><div class="task-row"><span class="fake-check"></span><div class="task-copy"><strong>Add registry destinations</strong><span>Links remain hidden until you mark them ready.</span></div><button class="chip go" data-view="registry">Open</button></div><div class="task-row"><span class="fake-check"></span><div class="task-copy"><strong>Review the guest website</strong><span>Only approved public details belong there.</span></div><button class="chip go" data-view="website">Preview</button></div></div></div><div><div class="section-title"><h2>How Grace fits</h2></div><div class="card card-pad grace-telegram"><span class="eyebrow">Conversation stays in Telegram</span><h3>Plan with Grace in your shared chat.</h3><p class="page-intro">Use this app for structured wedding data, guest-facing content, and account settings. Grace keeps the two connected without creating a second chat inbox.</p></div></div></div>`,
guests: () => pageHead('Guests & households','One thoughtful list for invitations, events, plus-ones, meals, and every person you care about.','147 people · 92 households',`<button class="button subtle demo" data-toast="CSV import is a prototype">Import CSV</button><button class="button primary demo" data-toast="Guest form opened">+ Add guest</button>`) + `
  <div class="grid four"><div class="card metric"><span class="label">People</span><strong>147</strong><small>Potential maximum</small></div><div class="card metric"><span class="label">Households</span><strong>92</strong><small>Invitation groups</small></div><div class="card metric"><span class="label">Plus-ones</span><strong>18</strong><small>11 still unnamed</small></div><div class="card metric"><span class="label">Need address</span><strong>23</strong><small>Ready to collect</small></div></div>
  <div class="section-title"><h2>Guest list</h2><span class="pill">Draft · private</span></div><div class="list-toolbar"><input class="search" id="guestSearch" placeholder="Search a name or household…"><button class="button subtle demo" data-toast="Filters opened">Filter</button><button class="button subtle demo" data-toast="Export preview generated">Export</button></div>
  <div class="card table-card"><table class="table" id="guestTable"><thead><tr><th>Guest</th><th>Events</th><th>RSVP</th><th>Address</th><th>Added by</th></tr></thead><tbody><tr class="household-row"><td colspan="5">Carlile household · 3 invited</td></tr>${guestRow('TC','Tom & Carrie Carlile','Parents · 2 guests','Wedding + Welcome','Attending','Complete','Tucker','green')}${guestRow('MC','Megan Carlile','Family · 1 guest','Wedding + Welcome','Waiting','Complete','Tucker','gold')}<tr class="household-row"><td colspan="5">Kim Matthews household · 2 potential</td></tr>${guestRow('KM','Aunt Kim Matthews','Family · plus-one allowed','Wedding','Draft','Missing','Tucker','gray')}<tr class="household-row"><td colspan="5">VanWagoner household · 2 invited</td></tr>${guestRow('SV','Sarah & Mark VanWagoner','Friends · 2 guests','Wedding','Attending','Complete','Syd','green')}</tbody></table></div>`,
website: () => {const preview=weddingPreviewDetails();return pageHead('Your wedding website','A romantic guest experience, safely separated from your private planning room.','Private preview · not published',`<a class="button subtle" href="../wedding/index.html">Open guest view ↗</a><button class="button primary demo" data-toast="Publish preview opened — nothing changed">Review prototype</button>`) + `
  <div class="preview-shell"><div class="card browser"><div class="browser-bar"><i></i><i></i><i></i><span>private-design-preview</span></div><div class="site-preview"><div class="site-preview-inner"><div class="tiny">Together with their families</div><h2>${preview.heading}</h2><p>${preview.date} · tentative</p><a class="button" href="../wedding/index.html">Enter preview</a></div></div></div><div><div class="card card-pad"><div class="status-line"><i></i>Not visible to guests</div><h3 style="font:500 22px var(--serif);margin:0 0 4px">Prototype changes ready</h3><p class="page-intro">This design preview cannot send or publish anything.</p><div class="edit-list"><div class="edit-row"><span>Travel note</span><span class="pill">Draft</span></div><div class="edit-row"><span>Floral gallery order</span><span class="pill">Draft</span></div><div class="edit-row"><span>Guest FAQ</span><span class="pill gold">Needs both</span></div></div><button class="button primary demo" data-toast="Approval preview opened" style="width:100%;margin-top:15px">Review changes</button></div><div class="card card-pad" style="margin-top:16px"><h3 style="margin-top:0">Pages</h3><div class="edit-list"><div class="edit-row"><span>Welcome</span><span>Preview</span></div><div class="edit-row"><span>Schedule</span><span>Draft</span></div><div class="edit-row"><span>Travel</span><span>Draft</span></div><div class="edit-row"><span>Registry</span><span>Draft</span></div></div></div></div></div>`},
rsvps: () => pageHead('RSVPs','A clear answer for every person, every event, and every detail.','Closes May 15, 2027',`<button class="button subtle demo" data-toast="RSVP form preview opened">Preview form</button><button class="button primary demo" data-toast="Reminder draft created — not sent">Draft reminder</button>`) + `
  <div class="grid four"><div class="card metric"><span class="label">Attending</span><strong>58</strong><small>39 households</small></div><div class="card metric"><span class="label">Declined</span><strong>10</strong><small>7 households</small></div><div class="card metric"><span class="label">Waiting</span><strong>79</strong><small>46 households</small></div><div class="card metric"><span class="label">Response rate</span><strong>46%</strong><small>Up 8% this week</small></div></div><div class="grid two"><div><div class="section-title"><h2>By event</h2></div><div class="card card-pad"><div class="category-row"><strong>Event</strong><strong>Yes</strong><strong>Waiting</strong></div><div class="category-row"><span>Wedding ceremony</span><strong>58</strong><span>79</span></div><div class="category-row"><span>Reception</span><strong>58</strong><span>79</span></div><div class="category-row"><span>Welcome party</span><strong>31</strong><span>22</span></div><div class="category-row"><span>Farewell brunch</span><strong>19</strong><span>34</span></div></div></div><div><div class="section-title"><h2>Needs attention</h2></div><div class="card"><div class="task-row"><span class="pill gold">4</span><div class="task-copy"><strong>Dietary notes to review</strong><span>Two allergies, two preferences</span></div><button class="chip demo" data-toast="Dietary responses shown">Review</button></div><div class="task-row"><span class="pill">11</span><div class="task-copy"><strong>Unnamed plus-ones</strong><span>Names can be added later</span></div><button class="chip demo" data-toast="Plus-one list shown">Open</button></div><div class="task-row"><span class="pill gray">3</span><div class="task-copy"><strong>Responses changed</strong><span>Since your last visit</span></div><button class="chip demo" data-toast="Recent changes shown">See</button></div></div></div></div>`,
registry: () => pageHead('Registry','One beautiful destination for the places and experiences you choose together.','Prototype · no registry connected',`<button class="button primary demo" data-toast="Registry link form opened">+ Add registry link</button>`) + `
  <div class="grid three"><div class="card registry-card"><div class="registry-icon">Z</div><h3>External registry</h3><p>Example link card<br>No account connected</p><div class="registry-actions"><button class="chip demo" data-toast="Example registry preview opened">Preview</button><button class="chip outline demo" data-toast="Registry settings opened">Settings</button></div></div><div class="card registry-card"><div class="registry-icon">⌂</div><h3>Home & garden</h3><p>Example collection<br>No items added</p><div class="registry-actions"><button class="chip demo" data-toast="Collection preview opened">Preview</button><button class="chip outline demo" data-toast="Registry settings opened">Settings</button></div></div><div class="card registry-card"><div class="registry-icon">✈</div><h3>Honeymoon link</h3><p>External-link placeholder<br>No fund connected</p><div class="registry-actions"><button class="chip demo" data-toast="Honeymoon preview opened">Preview</button><button class="chip outline demo" data-toast="Registry settings opened">Settings</button></div></div></div><div class="section-title"><h2>Guest experience</h2></div><div class="card card-pad"><div class="grid two"><div><span class="eyebrow">Registry wording draft</span><h2 style="font:500 25px var(--serif);margin:8px 0">Your presence is the greatest gift.</h2><p class="page-intro">For those who have asked, we've gathered a few things we would love as we begin this next chapter.</p></div><div><span class="pill gold">Private draft</span><p class="page-intro" style="margin-top:12px">Grace can help refine the wording, but both of you approve any registry change before it reaches guests.</p><button class="button subtle demo" data-toast="Wording editor opened">Edit wording</button></div></div></div>`,
tasks: () => pageHead('Tasks & decisions','Keep the work moving while preserving whose idea, preference, or decision it is.','8 open · 23 complete',`<button class="button primary demo" data-toast="New task form opened">+ Add task</button>`) + `
  <div class="grid two"><div><div class="section-title"><h2>Up next</h2><span class="pill">Prototype tasks</span></div><div class="card"><div class="task-row"><span class="fake-check"></span><div class="task-copy"><strong>Choose welcome party guest list</strong><span>Example joint-decision workflow</span></div><span class="attributed">Joint<br>decision</span></div><div class="task-row"><span class="fake-check"></span><div class="task-copy"><strong>Confirm Walloon Lake hold details</strong><span>Planning follow-up · no outreach sent</span></div><span class="pill gold">Example</span></div><div class="task-row"><span class="fake-check"></span><div class="task-copy"><strong>Review floral inspiration</strong><span>Based on Syd's saved board</span></div><span class="pill">Syd priority</span></div><div class="task-row"><span class="fake-check done">✓</span><div class="task-copy"><strong>Compare preliminary budget scenarios</strong><span>Planning models available · no joint budget set</span></div><span class="pill green">Prepared</span></div></div></div><div><div class="section-title"><h2>Waiting for both of you</h2><span class="pill gold">Example approvals</span></div><div class="grid"><div class="card decision-card"><span class="eyebrow">Guest experience</span><h3>Adults-only wording</h3><p>Tucker prefers an adults-only wedding. Syd has not confirmed this as a joint decision.</p><div class="decision-votes"><span class="pill green">Tucker · preference</span><span class="pill gold">Syd · not recorded</span></div></div><div class="card decision-card"><span class="eyebrow">Welcome event</span><h3>Who should see this event?</h3><p>Prototype example showing how event visibility would require an explicit couple decision.</p><div class="decision-votes"><span class="pill gold">Tucker · waiting</span><span class="pill gold">Syd · waiting</span></div></div></div></div></div>`,
budget: () => pageHead('Budget','A grounded view of estimates, scenarios, and what is still flexible.','Prototype planning view · no commitments recorded',`<button class="button subtle demo" data-toast="Budget export preview generated">Export preview</button><button class="button primary demo" data-toast="Estimate form opened">+ Add estimate</button>`) + `
  <div class="grid four"><div class="card metric"><span class="label">Joint budget</span><strong>Not set</strong><small>No final couple decision</small></div><div class="card metric"><span class="label">Committed</span><strong>$0</strong><small>Prototype records none</small></div><div class="card metric"><span class="label">Paid</span><strong>$0</strong><small>No payments tracked</small></div><div class="card metric"><span class="label">Scenarios</span><strong>3</strong><small>Planning ranges to compare</small></div></div><div class="section-title"><h2>Illustrative category planning</h2></div><div class="card card-pad"><div class="budget-bar"><span></span><span></span><span></span><span></span></div><div class="category-row"><strong>Category</strong><strong>Status</strong><strong>Source</strong></div><div class="category-row"><span>Venue & catering</span><strong>Comparing</strong><span>Provisional ranges</span></div><div class="category-row"><span>Photography & video</span><strong>Not selected</strong><span>Placeholder</span></div><div class="category-row"><span>Florals & decor</span><strong>Priority</strong><span>Syd preference</span></div><div class="category-row"><span>Music & entertainment</span><strong>Not selected</strong><span>Placeholder</span></div><div class="category-row"><span>Attire, stationery & other</span><strong>Not selected</strong><span>Placeholder</span></div></div>`,
vendors: () => pageHead('Vendors','Research and conversations organized without implying a commitment.','Planning preview · nothing booked here',`<button class="button primary demo" data-toast="Vendor form opened">+ Add vendor idea</button>`) + `
  <div class="grid two"><div class="card vendor-card"><div class="vendor-logo">W</div><div class="vendor-copy"><h3>Walloon Lake Country Club</h3><p>Venue & catering · Walloon Lake, MI</p><div class="vendor-meta"><span class="pill gold">Under consideration</span><span class="pill">June 26 hold</span><span class="pill gray">Not booked</span></div></div></div><div class="card vendor-card"><div class="vendor-logo">P</div><div class="vendor-copy"><h3>Photographer shortlist</h3><p>Sample workflow · no vendor selected</p><div class="vendor-meta"><span class="pill">Research placeholder</span><span class="pill gray">No commitment</span></div></div></div><div class="card vendor-card"><div class="vendor-logo">F</div><div class="vendor-copy"><h3>Floral direction</h3><p>Airy wild-garden inspiration</p><div class="vendor-meta"><span class="pill gold">Syd priority</span><span class="pill">Mood board saved</span><span class="pill gray">No vendor selected</span></div></div></div><div class="card vendor-card"><div class="vendor-logo">DJ</div><div class="vendor-copy"><h3>Music shortlist</h3><p>Sample workflow · no vendor selected</p><div class="vendor-meta"><span class="pill">Not started</span><span class="pill gray">Prototype</span></div></div></div><div class="card vendor-card"><div class="vendor-logo">C</div><div class="vendor-copy"><h3>Ceremony music</h3><p>No vendor selected yet</p><div class="vendor-meta"><span class="pill gray">Not started</span></div></div></div><div class="card vendor-card"><div class="vendor-logo">H</div><div class="vendor-copy"><h3>Hotel room blocks</h3><p>Future planning workflow</p><div class="vendor-meta"><span class="pill gold">Needs research</span><span class="pill gray">No outreach sent</span></div></div></div></div>`,
 settings: () => settingsView(pageHead)
};

views.guests = () => guestsView(pageHead);
views.rsvps = () => rsvpsView(pageHead);
views.registry = () => registryView(pageHead);
views.settings = () => settingsView(pageHead);

function pageHead(title,intro,kicker,actions=''){return `<section class="page"><header class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p class="page-intro">${intro}</p></div><div class="head-actions">${actions}</div></header>`}
function guestRow(initials,name,detail,events,rsvp,address,by,status){return `<tr data-search="${name.toLowerCase()}"><td><div class="person"><span class="person-dot">${initials}</span><div><strong>${name}</strong><small>${detail}</small></div></div></td><td>${events}</td><td><span class="pill ${status}">${rsvp}</span></td><td>${address}</td><td>${by}</td></tr>`}

function showView(name, push=true){
  if(!views[name]) name='overview';
  workspace.innerHTML = views[name]() + (name==='room' ? '' : '</section>');
  $$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));
  $$('.mobile-nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));
  $('#sidebar').classList.remove('open'); $('#mobileMenu').setAttribute('aria-expanded','false'); workspace.focus({preventScroll:true}); window.scrollTo(0,0);
  bindView(name); if(push) history.replaceState(null,'',`#${name}`);
}
function bindView(name){
  $$('.go',workspace).forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  $$('.demo',workspace).forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast||'Demo interaction')));
  const form=$('#composer'); if(form) form.addEventListener('submit',e=>{e.preventDefault();const input=$('#chatInput');if(!input.value.trim())return;toast('Grace received your message — demo only');input.value=''});
  const undo=$('#undoAunt'); if(undo) undo.addEventListener('click',()=>{const c=$('#auntAction');c.innerHTML='<div class="action-title"><span class="check" style="background:#887276">↶</span>Change undone</div><div class="action-body">Aunt Kim was returned to her previous draft state. Your activity history still shows what happened.</div>';toast('Guest change undone')});
  const openAccount=$('#openAccountMenu'); if(openAccount) openAccount.addEventListener('click',e=>{e.stopPropagation();$('#accountMenu').classList.add('open')});
  const passwordForm=$('#passwordForm'); if(passwordForm) passwordForm.addEventListener('submit',async e=>{e.preventDefault();const next=$('#newPassword'),confirm=$('#confirmNewPassword'),notice=$('#passwordNotice'),submit=e.currentTarget.querySelector('[type="submit"]');if(next.value!==confirm.value){notice.textContent='The two passwords do not match.';confirm.focus();return}submit.disabled=true;submit.textContent='Updating…';const{error}=await supabase.auth.updateUser({password:next.value});if(error){notice.textContent='We could not update your password. Try again in a moment.';submit.disabled=false;submit.textContent='Update password';return}e.currentTarget.reset();notice.textContent='Password updated.';submit.disabled=false;submit.textContent='Update password'});
  const search=$('#guestSearch');if(search)search.addEventListener('input',()=>{$$('#guestTable tbody tr').forEach(row=>{if(row.classList.contains('household-row'))return;row.style.display=row.dataset.search.includes(search.value.toLowerCase())?'':'none'})});
  bindLiveView(name, toast).catch(error => {
    const target = name === 'guests' ? $('#liveGuestList') : name === 'registry' ? $('#liveRegistry') : name === 'settings' ? $('#memberAccessList') : name === 'rsvps' ? $('#rsvpHelpList') : null;
    if (target) target.innerHTML = `<div class="empty-note">${escapeHtml(error.message || 'Could not load this section.')}</div>`;
  });
}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
$$('[data-view]', $('#mainNav')).forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$$('.mobile-nav [data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('#mobileMenu').addEventListener('click',e=>{const open=$('#sidebar').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
$('#accountButton').addEventListener('click',e=>{e.stopPropagation();const open=$('#accountMenu').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
$('#accountSettings').addEventListener('click',e=>{e.preventDefault();showView('settings');$('#accountMenu').classList.remove('open')});
document.addEventListener('click',()=>{$('#accountMenu').classList.remove('open');$('#accountButton').setAttribute('aria-expanded','false')});
showView(location.hash.slice(1)||'overview',false);
